included:
    - Geochatter
whitelist_rules:
    - attributes
    - closing_brace
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - colon
    - comma
    - control_statement
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - horizontal_whitespace
    - leading_whitespace
    - let_var_whitespace
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - multiple_closures_with_trailing_closure
    - no_space_in_method_call
    - opening_brace
    - operator_usage_whitespace
    - operator_whitespace
    - protocol_property_accessors_order
    - redundant_discardable_let
    - return_arrow_whitespace
    - shorthand_operator
    - switch_case_alignment
    - trailing_closure
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - unneeded_parentheses_in_closure_argument
    - unused_optional_binding
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition
