name: Build Develop

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clean and build debug version of app
        run: |
          xcodebuild clean -workspace Geochatter.xcworkspace -scheme Geochatter
          xcodebuild build -workspace Geochatter.xcworkspace -scheme Geochatter CODE_SIGN_IDENTITY="" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" CODE_SIGNING_REQUIRED="NO"
