name: Build Develop

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          xcodebuild clean -workspace Geochatter.xcworkspace -scheme Geochatter
          xcodebuild build -workspace Geochatter.xcworkspace -scheme Geochatter
